### ISSUE TITLE
Not Found: LeddarConfigurator4.lib 

### ISSUE THREAD

**Issue by amnsr17** [leddartech/LeddarSDK#11]
While trying to run LeddarPy.sln in the SDK, I am having this error:
LNK1181: cannot open input file '..\LeddarConfigurator4\x64\Release\LeddarConfigurator4.lib'
There is no directory named x64 in LeddarConfigurator4 in the project.
Why am I getting this error? and any pointers on how to solve it?
![image](https://user-images.githubusercontent.com/42863139/72151067-098e8680-33c9-11ea-97d9-c0ac1b7de91a.png)

**Comment by amnsr17** [comment]
@support-leddartech 
I am using Visual Studio 2019 and Yes I compiles LeddarConfigurator4.sln before running LeddarPy.sln

**Comment by support-leddartech** [comment]
Hi @amnsr17,

Please send us an email at support@leddartech.com so we can provide you with some training material which will allow you to successfully get the SDK running with the Python examples.

Thank you,

- LeddarTech Support Team
