### ISSUE TITLE
LeddarOne UART Speed too low

### ISSUE THREAD

**Issue by ashwinvk94** [leddartech/LeddarSDK#20]
Hi,

I am using the LeddarOne using the LeddarSDK. I am using a usb to uart converter to interface with the sensor. I was able to receive data both using the **LeddarExample based on SDK 4.3.0.107** script and then the a separate python script using the **python SDK**.

But in both cases the refresh rate was only around 8Hz. But [this spec document](
https://leddartech.com/app/uploads/dlm_uploads/2018/04/LeddarOne_specsheet_2020_EN.pdf) mentions a data refresh rate of upto **140Hz**. How can I increase the refresh rate to 140Hz?

**Comment by JulienStanguennec-Leddartech** [comment]
Hi Ashwin,

To get the LeddarOne to work at 140 Hz, a couple of parameters needs to be adjusted. As described in the [LeddarOne's user-guide](https://d2euypccftd53r.cloudfront.net/prod/app/uploads/2019/05/07143411/54A0025-4-Leddar-One-User-Guide.pdf), the section "3.4 measurement rate" explains that it's essentially set by these two acquisition settings accumulation and oversampling (see below).   
![image](https://user-images.githubusercontent.com/44166203/95399362-02ec5b80-08d6-11eb-9b4d-ff21110dccba.png)

To set these two parameters you may use our software [LeddarConfigurator (windows only)](https://leddartech.com/resources/#leddarone-en&product-download/) which comes with a GUI, or simply use the LeddarExample bundled with this SDK.

### Sensor configuration with LeddarExample from LeddarSDK ###

With LeddarExample, once connected to your LeddarOne you should have the following menu in the terminal:
![image](https://user-images.githubusercontent.com/44166203/95399535-61b1d500-08d6-11eb-9c25-1e87c7f68e81.png)

Select "4 - Change configuration" (Press "4" then "enter"), and the following menu should appear:
![image](https://user-images.githubusercontent.com/44166203/95399685-b6ede680-08d6-11eb-9dee-862f813e5716.png)

Accumulation and oversampling are configurable through a register that contains the power of 2 of the number of the parameter. In our case, we will change Accumulation exponent to 7 (2^7 = 128), and Oversampling exponent to 2 (2^2=4)

**Set Accumulation exponent to 7:**
![image](https://user-images.githubusercontent.com/44166203/95400165-ee10c780-08d7-11eb-8585-7c1ebe1c2007.png)

**Set Oversampling exponent to 2:**
![image](https://user-images.githubusercontent.com/44166203/95400101-c6216400-08d7-11eb-9e8a-97ec016fe72e.png)

Then the sensor is configured properly to run at 140 Hz.

### Adjustment to timings within the source code ###

However, some adjustment needs to be done to the code to optimize its execution:
- In _/LeddarSDK/src/shared/comm/Modbus/LtComLeddarOneModbus.h_, on the line 29, modify the `#define ONE_WAIT_AFTER_REQUEST 2000` to `#define ONE_WAIT_AFTER_REQUEST 1200`, to improve the delay in communication. 
- In _/LeddarSDK/src/LeddarExample/LeddarExample.cpp_, on the line 487, change the `LeddarUtils::LtTimeUtils::Wait( 1 );` to `LeddarUtils::LtTimeUtils::WaitBlockingMicro(500)` to accelerate the execution of the code.

### Adjustment latency parameters if using FTDI USB converter ###

Finally, if you use an FTDI USB converter, you would need to set the device to low latency (1ms), the following documentation :
- For Linux: external link [changing ttyUSB0/latency_timer file](https://granitedevices.com/wiki/FTDI_Linux_USB_latency) or [setserial](https://lore.kernel.org/patchwork/patch/763419/)
- For Windows: document attached. [USB to Serial port Optimized settings.pdf](https://github.com/leddartech/LeddarSDK/files/5348883/USB.to.Serial.port.Optimized.settings.pdf)

**Note:** The execution of the code in the terminal or the command prompt can also slow down the process, so you can also comment the _std::cout_ and use the record feature. Please contact me at support@leddartech.com, should you need any additional assistance.

Best regards,
Julien Stanguennec.

**Comment by ashwinvk94** [comment]
Thanks Julien, for the detailed explanation to debug this issue. I have used the

**Comment by ashwinvk94** [comment]
Hi Julien,

Thanks for the quick response. I had missed out the details in the user-guide. I was able to receive data at 120Hz on rostopic after changing the Accumulation exponent to 7 and Oversampling exponent to 2.
