### ISSUE TITLE
LeddarSDK/src/Leddar_ROS

### ISSUE THREAD

**Issue by Hyeji-KIM-temp** [leddartech/LeddarSDK#22]
I received the Leddar Vu8's data using Leddar_ROS SDK.

The data is received well, but data updated by 1 Hz.

I want to up the receiving frequency.

How can I this?

**Comment by JulienStanguennec-Leddartech** [comment]
Hi KIM,

I would recommend to take a look at this similar issue #20 with LeddarOne to get a better understanding of how to set the frame rate with your sensor. 

Essentially, two parameters comes into play when setting the sensors frame rate (accumulation and oversampling). These parameters can be easily set with LeddarConfigurator (WIndows only), or with LeddarSDK.

As you may have seen from the architecture, LeddarSDK is based on C++, on which we provide a [python wrapper](http://sdk.leddartech.com/v4.3/#/Python?id=python-interface) used for our [ROS driver](http://sdk.leddartech.com/v4.3/#/ROS?id=leddar_ros).

<img src="https://user-images.githubusercontent.com/44166203/104751400-56ffab00-5723-11eb-9aaf-dfee8926dd70.png" width="400" height="400">

The LeddarPy API offers a [Device class](https://sdk.leddartech.com/v4.3/#/Python?id=device-class), which offers methods to change any property and specific methods to change directly accumulation and oversampling exponents:

- To change the accumulation exponent you may, use this method `dev.set_accumulation_exponent(new_value)`.
- To change the oversampling exponent you may, use this method `dev.set_oversampling_exponent(new_value)`.

With leddar_ros, `catkin_ws/src/leddar_ros/scripts/device.py` [here](https://github.com/leddartech/LeddarSDK/blob/master/src/Leddar_ROS/scripts/device.py) is the script that publishes the point cloud data. It create a leddardevice object `dev = leddar.device()` and the connect method to connect `dev.connect(param1,device_type,param3,param4)`. 

You chould use the set_accumulation exponent method after connection. At the time, I am writing this answer, it should be on line 58 of the `leddar_ros/scripts/device.py`

![leddar_ros-script-device-py](https://user-images.githubusercontent.com/44166203/104757926-a6e27000-572b-11eb-8624-2c2b0f9a2c86.png)


You may find more information on how to calculate frame-rate in the [LeddarVu8's user-guide](https://leddartech.com/solutions/leddar-vu8-solid-state-lidar-sensor-module/). At the time, I am writing this response, I have taken a screen capture of the 54A0028-6 version of the user-guide. Please make sure you take the latest version on our website.

![measurement_rate_vu8-](https://user-images.githubusercontent.com/44166203/104752623-e5286100-5724-11eb-947a-9742595bb3a3.png)

Let me know, if it answers your question.

Have a great weekend!

Best regards,
Julien Stanguennec.

**Comment by JulienStanguennec-Leddartech** [comment]
I will consider this case closed.
