### ISSUE TITLE
Leddar Pixell

### ISSUE THREAD

**Issue by Magmanat** [leddartech/LeddarSDK#23]
I am intending to purchase some Leddar Pixells to try and implement in my robot for ros, may i know if i can get the pointcloud data from the Leddar pixell using this Leddar_ros launch?

**Comment by JulienStanguennec-Leddartech** [comment]
Hi @Magmanat ,

Sorry for the delay of my answers. 

The answer is yes we can definitly use Pixell sensor with Leddar_ros launch file. As described onto this SDK overview ; [https://leddartech.com/must-read-guide-new-leddarsdk](https://leddartech.com/must-read-guide-new-leddarsdk)/, and in the architecture below:

![image](https://user-images.githubusercontent.com/44166203/106949590-27790880-66fb-11eb-8040-167560007018.png)

leddar_ros will use the python module of LeddarSDK to create the node that would publish the PointCloud2 topic.

If you need any additional documentation on how to use leddar_ros, you could refer to [http://sdk.leddartech.com/v4.3/#/ROS?id=leddar_ros](http://sdk.leddartech.com/v4.3/#/ROS?id=leddar_ros)

Should you have any question, feel free to ask or open another issue.

I believe this would closed the case, as it is a fairly non-technical question.

Best regards,
Julien Stanguennec.
