### ISSUE TITLE
Connecting with Leddar Vu8 using USB

### ISSUE THREAD

**Issue by wasih123** [leddartech/LeddarSDK#3]
Hello
I have a Vu8 and I bought a USB type-A cable to connect it with the USB hub on my board(Jetson TX2). The problem comes when I run the python example of LeddarPy package.
As is clear from the code, direct USB connection is not supported by the SDK for Vu8. How do I connect with serial modbus using the USB cable as I don't have a serial port on the board?
If this is not possible, how can I connect it alternatively? Please provide a detailed procedure preferably using the USB cable as a serial modbus connection.

**Comment by DavidSarrasin-Leddartech** [comment]
Dear Wasih123,
Thank you for contacting us at Leddartech.
Your support inquiry has been received and is currently being reviewed by our team.

We will get back to you with an answer shortly.

Thank you for bearing with us on this.
Best regards,

**Comment by DavidSarrasin-Leddartech** [comment]
Dear Wasih123,

Sorry for the delay in getting back to you.

It is indeed not possible to connect to the LeddarVu8 sensor through USB and use our SDK. We usually suggest to connect to the sensor using an FTDI USB-RS-485-WE cable (see picture below).

![1](https://user-images.githubusercontent.com/44166575/58437222-098a8200-8097-11e9-949a-91eb33798c09.png)

You can find the LeddarVu8 User Guide here:
https://support.leddartech.com

Let us know should you have any further question. We will be pleased to assist you.
Best regards,
David
