### ISSUE TITLE
LdObject disconnect fails for duplicate connections

### ISSUE THREAD

**Issue by markuspg** [leddartech/LeddarSDK#4]
Hi,

thank you for supplying the SDK. I'm currently exploring it. I think found an issue with LdObject's connection functionality.

I was testing the correct disconnect of duplicate connections. It seems duplicate connections that got created one after each other are not disconnected properly. I suspect the increment of lIter on line 82 of LdObject.cpp is to blame. The next element in the list is skipped because this leads to a double increment with the increment in the for loop.

A sample I created here: https://github.com/markuspg/LeddarSDK/blob/disconnectIssueSample/tests/LeddarTest/main.cpp

Perhaps a workaround would be to decrement lIter in line 82 instead?

Best,
markuspg

**Comment by DavidLevy-Leddartech** [comment]
Thanks for reporting the issue, I'll take a look

**Comment by DavidLevy-Leddartech** [comment]
Fixed in commit a7b5b059b4f26352437058ccda71b7caba4b44e0
It's pointless to have the same connection with the same signal twice (callback would be called twice), so we prevent it.
