### ISSUE TITLE
ROS Package - Vu8 - Serial - USB communication problem

### ISSUE THREAD

**Issue by veervishu99** [leddartech/LeddarSDK#5]
I am launching  ROS package provided by you but during communication, I am getting a connection issue in it. Is there any specific format required for serial no. or something else.
--------------------------------------------------------
I provided the following command:
roslaunch leddar_ros example.launch param1:=DI3500207 device_type:=Vu8
--------------------------------------------------------
then I get this error

process[rviz-3]: started with pid [29562]
[ INFO] [1561096376.293109957]: rviz version 1.12.17
[ INFO] [1561096376.293170633]: compiled against Qt version 5.5.1
[ INFO] [1561096376.293177437]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1561096376.407115703]: Stereo is NOT SUPPORTED
[ INFO] [1561096376.407187344]: OpenGl version: 3 (GLSL 1.3).
[ERROR] [1561096376.604497]: Error connecting to device type Vu8 with connection info DI3500207/0/0.
Traceback (most recent call last):
  File "/home/*<user>*/catkin_ws/src/leddar_ros/scripts/device.py", line 57, in <module>
    raise RuntimeError(err_msg)
RuntimeError: Error connecting to device type Vu8 with connection info DI3500207/0/0.

**Comment by veervishu99** [comment]
I am getting this error and not solved yet

**Comment by DavidLevy-Leddartech** [comment]
Sorry for the delay, I was in hollyday.

Your param1 is probably wrong. You can check the exact parameters in launch/example.launch. It willl probably be something like /dev/ttyASM1
