### ISSUE TITLE
Leddar M16 ROS Launch Problem

### ISSUE THREAD

**Issue by kvynlim** [leddartech/LeddarSDK#8]
The output of: roslaunch leddar_ros example.launch param1:=AK47035 device_type:=M16

... logging to /home/kvyn/.ros/log/1968fc34-fa26-11e9-8665-80a58978f877/roslaunch-Kvyn-10350.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Kvyn:42203/

SUMMARY
========

PARAMETERS
 * /LeddarTech_1/sensor/device_type: M16
 * /LeddarTech_1/sensor/frame_id: sensor_frame
 * /LeddarTech_1/sensor/param1: AK47035
 * /LeddarTech_1/sensor/param3: 0
 * /LeddarTech_1/sensor/param4: 0
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /LeddarTech_1/
    leddar_1_to_map (tf/static_transform_publisher)
    sensor (leddar_ros/device.py)
  /
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [10360]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1968fc34-fa26-11e9-8665-80a58978f877
process[rosout-1]: started with pid [10371]
started core service [/rosout]
process[LeddarTech_1/sensor-2]: started with pid [10377]
process[LeddarTech_1/leddar_1_to_map-3]: started with pid [10379]
process[rviz-4]: started with pid [10380]
[ INFO] [1572337716.147842922]: rviz version 1.13.4
[ INFO] [1572337716.147885644]: compiled against Qt version 5.9.5
[ INFO] [1572337716.147898850]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1572337716.151850532]: Forcing OpenGl version 0.
[ INFO] [1572337716.461546721]: Stereo is NOT SUPPORTED
[ INFO] [1572337716.461673450]: OpenGl version: 3 (GLSL 1.3).
**[ERROR] [1572337716.600246]: Error connecting to device type M16 with connection info AK47035/0/0.
Traceback (most recent call last):
  File "/home/kvyn/catkin_ws/src/leddar_ros/scripts/device.py", line 57, in <module>
    raise RuntimeError(err_msg)
RuntimeError: Error connecting to device type M16 with connection info AK47035/0/0.
[LeddarTech_1/sensor-2] process has died [pid 10377, exit code 1, cmd /home/kvyn/catkin_ws/src/leddar_ros/scripts/device.py __name:=sensor __log:=/home/kvyn/.ros/log/1968fc34-fa26-11e9-8665-80a58978f877/LeddarTech_1-sensor-2.log].
log file: /home/kvyn/.ros/log/1968fc34-fa26-11e9-8665-80a58978f877/LeddarTech_1-sensor-2*.log**

Is the param1 and device type wrong? If yes, what is the correct value for param1 and device type

**Comment by kvynlim** [comment]
@DavidLevy-Leddartech

**Comment by support-leddartech** [comment]
Hi kvynlin,

From my analysis, I believe that your issue stems from "param1". This value needs to be the serial number of your sensor, which is indicated on your unit. We will modify the Launch section in order to specify this.

If your device is indeed an M16 and you input your serial number as "param1", you should have your unit working with RViz if you've followed the deployment steps and its required installations.

Let us know how this works out - we're always here to help !

~ LeddarTech Support Team

**Comment by kinglolo** [comment]
Hi, I am also facing the same issue.
this shows in my console after I run the roslaunch :

process[rviz-3]: started with pid [12552]
[ INFO] [1577352846.661665519]: rviz version 1.13.4
[ INFO] [1577352846.661729977]: compiled against Qt version 5.9.5
[ INFO] [1577352846.661752194]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1577352846.674990030]: Forcing OpenGl version 0.
Traceback (most recent call last):
  File "/home/weitinglo/catkin_ws/src/leddar_ros/scripts/device.py", line 39, in <module>
    dev = leddar.Device()
AttributeError: 'module' object has no attribute 'Device'

If there is a solution for this problem, please let me know as well :).
Thanks in advance!
